apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: my-frontend:latest # <-- The image we built in Step 2
          imagePullPolicy: Never # <-- IMPORTANT: Tells K8s not to look on the internet for it
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # <-- This type is designed to be exposed externally
  selector:
    app: frontend # Finds pods with the "app: frontend" label
  ports:
    - port: 80 # The port others will use to access it
      targetPort: 80 # The port on the container