apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  # ReadWriteOnce means it can only be mounted by one node at a time
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # You can adjust this size
      storage: 1Gi