apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  # This service finds any pod with the 'app: db' label
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432