apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  # Change this password!
  POSTGRES_PASSWORD: "postgreSQL Password"
  # We also set the user here for consistency
  POSTGRES_USER: "YourUser"