apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # Type LoadBalancer will 'provision' an external IP
  # In Minikube, this requires 'minikube tunnel' to work
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      # The port the service will be available on
      port: 80
      # The port on the pod (Nginx) to send traffic to
      targetPort: 80